### ISSUE TITLE
Signal-Generator compile error

### ISSUE THREAD

**Issue by ChuckDorval** [RTXI/signal-generator#1]
Yo! Trying to install some standard modules, and having an issue with signal-generator compiling.
I could muck with default_gui_model.h, but I figure I shouldn't need to. Thoughts on make error below? - Chuck

In file included from signal-generator.h:19:0,
                 from signal-generator.cpp:19:
/usr/local/include/rtxi/default_gui_model.h: In member function 'void SigGen::customizeGUI()':
/usr/local/include/rtxi/default_gui_model.h:280:19: error: 'QMdiSubWindow\* DefaultGUIModel::subWindow' is private
    QMdiSubWindow *subWindow;
                   ^
signal-generator.cpp:226:2: error: within this context
  subWindow->adjustSize();

**Comment by sudorook** [comment]
Ah, yeah, that's a bug. And yes, you shouldn't need to muck about in default_gui_model.h. 

I pushed a fix to the module repo. 

What I did was move that function call to the constructor, and instead of using `adjustSize`, I used a wrapper function from default-gui called `resizeMe`. (Just FYI - there's no need for you to know that to use the module.) 

Let me know if that fixes it for you. Thanks.

**Comment by ChuckDorval** [comment]
Problem resolved Ansel. Thanks!
